config/routes.rb
Rails.application.routes.draw do
  # Rails knows that somehow we will add links to certain pages to navigate between them.
  #  As an end user, you would not like to type URLs all the time to go to a certain page and view that certain page to another one.
  # We are very familiar with links: they make our life easy.

  get "/owners", to: "owners#index", as: :owners

  # This will create a owners_path helper method: is going to take me to the combination of "Get and /owners""
  # The prefix is whatever comes before path. The path part is added automatically
  # So owners_path gets me this route -->   get '/owners', to: 'owners#index' and would take me to the index page.
  # Without the helpers, if we would like to specify a link to a certain page, we would need to specify the http verb, and the URI.
  # While with the helpers, we could just say just use owners_path and it would take us to the owners index page.
  # Basically each of the templates in the views has its own helper.

  # GET routes
  get "/owners/new", to: "owners#new", as: :new_owner
  get "/owners/:id/edit", to: "owners#edit", as: :edit_owner
  get "/owners/:id", to: "owners#show", as: :owner

  # Other routes
  post "/owners", to: "owners#create"
  patch "/owners/:id", to: "owners#update"
  delete "/owners/:id", to: "owners#destroy"

  # Helpers are only for Get HTTP requests. No helpers for the operations that happen only at the database level.
  # For Create, Update and Destroy, there is no page to see, again because these just happen behind the scenes,
  # there is no helper provided for this operation. We cannot link to a page for create/Update/Destroy

  # All the above could be simply replaced by
  # resources :owners

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :pets
  resources :animals
  resources :visits
  resources :dosages
  resources :treatments
  resources :medicines
  resources :procedures

  # Routes for mecidine and procedure costs
  # In some cases, we would like to create our own routes.
  # For example, let's say we say that there should not be an index page for medicine cost,
  #  If we were to open medicine_cost in PATS, we did not design a whole index page for it, but associated it instead with a particular medicine.
  # A particular cost could be added this way, and the costs  of a certain medicine including the one we added can be displayed only on this one page
  #  in addition to the details of the medicine.
  #  There is no need to create a full index page of all teh costs page with medicine cost.
  # So, in this particular case, we would not want to use resources, but rather create the paths manually.
  #  Add routes for the functions offered only: so, we need a form to add a new medicine_cost.
  # We specify the:
  # - get: my http verb
  # - my URL: medicine_cost/new
  # Map to this controller#action combination, and then this 'as', this is where I am creating for myself a named helper.
  # So if I say new_medicine_cost_path, it would take me to that empty form to fill it and create a new medecine
  get "medicine_costs/new", to: "medicine_costs#new", as: :new_medicine_cost
  get "procedure_costs/new", to: "procedure_costs#new", as: :new_procedure_cost

  post "medicine_costs", to: "medicine_costs#create", as: :medicine_costs
  post "procedure_costs", to: "procedure_costs#create", as: :procedure_costs

  # Semi-static page routes
  get "home", to: "home#index", as: :home
  get "home/about", to: "home#about", as: :about
  get "home/contact", to: "home#contact", as: :contact
  get "home/privacy", to: "home#privacy", as: :privacy
  # You can have the root of your site routed with 'root'
  root "home#index"

  get "home/search", to: "home#search", as: :search
  # Routes for searching
  # get 'medicines/search', to: 'medicines#search', as: :medicine_search
  # get 'owners/search', to: 'owners#search', as: :owner_search
  # get 'pets/search', to: 'pets#search', as: :pet_search



  # Authentication routes
  resources :users


  resources :sessions


  get "users/new", to: "users#new", as: :signup
  get "users/:id/edit", to: "users#edit", as: :edit_current_user


  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
end

app/models/pet.rb
class Pet < ApplicationRecord
  # Relationships
  # -----------------------------
  belongs_to :animal
  belongs_to :owner
  has_many :visits
  has_many :dosages, through: :visits
  has_many :treatments, through: :visits
  # has_many :notes, as: :notable


  # Scopes
  # -----------------------------
  # order pets by their name
  scope :alphabetical, -> { order('name') }
  # get all the pets we treat (not moved away or dead)
  scope :active, -> { where(active: true) }
  # get all the pets we heave treated that moved away or died
  scope :inactive, -> { where.not(active: true) }
  # alternative ways of doing the inactive scope:
  # scope :inactive, -> { where(active: false) }
  # scope :inactive, -> { where('active = ?', true) }
  # get all the female pets
  scope :females, -> { where(female: true) }
  # get all the male pets
  scope :males, -> { where(female: false) }

  # get all the pets for a particular owner
  scope :for_owner, ->(owner_id) { where("owner_id = ?", owner_id) }
  # get all the pets who are a particular animal type
  scope :by_animal, ->(animal_id) { where("animal_id = ?", animal_id) }
  # get all the pets born before a certain date
  scope :born_before, ->(dob) { where('date_of_birth < ?', dob) }
  # find all pets that have a name like some term or are and animal like some term
  scope :search, ->(term) { where('pets.name LIKE ?', "#{term}%").order("pets.name") }


  # Validations
  # -----------------------------
  # System note:   not requiring DOB because may not be known (e.g., adopted pet)
  # Teaching note: could have done validates_presence_of :name, but using a different
  #                method discussed in class to show alternative
  #
  # First, make sure a name exists
  validates :name, presence: true
  # Second, make sure the animal is one of the types PATS treats
  validate :animal_type_treated_by_PATS
  # Third, make sure the owner_id is in the PATS system 
  validate :owner_is_active_in_PATS_system
  

  # Misc Methods and Constants
  # -----------------------------
  # a method to get owner name in last, first format
  def gender
    return "Female" if self.female
    "Male"
    # self.female ? "Female" : "Male"
    # if self.female 
    #   return "Female"
    # else
    #   return "Male"
    # end
  end  
  
  
  # Use private methods to execute the custom validations
  # -----------------------------
  private
  def animal_type_treated_by_PATS
    # get an array of all animal ids PATS treats
    treated_animal_ids = Animal.all.map{|a| a.id}
    # add error unless the animal id of the pet is in the array of possible animal ids
    unless treated_animal_ids.include?(self.animal_id)
      errors.add(:animal, "is an animal type not treated by PATS")
    end
  end
  
  def owner_is_active_in_PATS_system
    # get an array of all active owners in the PATS system
    all_owner_ids = Owner.active.all.map{|o| o.id}
    # add error unless the owner id of the pet is in the array of active owners
    unless all_owner_ids.include?(self.owner_id)
      errors.add(:owner, "is not an active owner in PATS")
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  # A callback to set up an @pet object to work with 
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    # get data on all pets and paginate the output to 10 per page
    @active_pets = Pet.active.alphabetical.paginate(page: params[:page]).per_page(10)
    @inactive_pets = Pet.inactive.alphabetical.to_a

    # render template[:index]
    # layout 'application'
  end

  def show
    # Show the pet's details using id; done with before_action
    # @pet = Pet.find(params[:id])

    # get the last 10 visits for this pet
    @recent_visits = @pet.visits.chronological.last(10).to_a

    # render template[:show]
    # layout 'application'
  end

  def new
    # create an empty pet object to populate with data
    @pet = Pet.new

    # render template[:new]
    # layout 'application'
  end

  def edit
    # get @pet... before_action does the following:
    # @pet = Pet.find(params[:id])
    # render template[:edit]
    # layout 'application'
  end

  def create
    # create a pet object with filtered parameters
    @pet = Pet.new(pet_params)
    # attempt to save the pet object
    if @pet.save
      # if save happened, redirect to pets#show for this new pet
      redirect_to pet_path(@pet), notice: "Successfully added #{@pet.name} as a PATS pet."
    else
      # re-render the new action with the errors displayed
      render action: 'new'
    end
  end

  def update
    # a similar process to #create
    if @pet.update(pet_params)
      redirect_to @pet, notice: "Updated #{@pet.name}'s information"
    else
      render action: 'edit'
    end
  end

  def destroy
    # find the pet object with before_action first
    @pet.destroy
    # redirect back to the pets#index listing
    redirect_to pets_url, notice: "Removed #{@pet.name} from the PATS system"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pet
    @pet = Pet.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def pet_params
    params.require(:pet).permit(:name, :animal_id, :owner_id, :female, :date_of_birth, :active)
  end

end

app/views/pets/_active_pets.html.erb
<h4>Active Pets at PATS</h4>

<table class="table table-striped table-hover table-borderless">
  <thead>
    <th>Pet</th>
    <th>Type</th>
    <th>Owner</th>
    <th class="align_center">Options</th>
  </thead>
  <% for pet in @active_pets %>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
      <td><%= link_to pet.name, pet_path(pet) %></td>
      <td><%= pet.animal.name %></td>
      <td><%= link_to pet.owner.name, owner_path(pet.owner) %></td>

    <td class="align_center">
      <%= link_to edit_pet_path(pet) do %>
            <i class="bi bi-pencil text-primary"></i>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to(pet_path(pet), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
            <i class="bi bi-trash text-primary"></i>
        <% end %>
    </td>
    </tr>
  <% end %>
</table>
<p class="supertiny"></p>
<%= will_paginate @active_pets, renderer: BootstrapPaginationHelper::BootstrapLinkRenderer %>
<p class="supertiny">&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'pet'} %>

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :name, label_html: { class: 'active' } %>
      <%= f.input :animal_id, collection: Animal.alphabetical.active.to_a, include_blank: true %>
      <%= f.input :owner_id, collection: Owner.alphabetical.active.to_a, include_blank: true %>
      <%= f.input :date_of_birth, label_html: { class: 'active' } %>
      <%= f.input :female, as: :radio_buttons %>
      <%= f.input :active %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col-md-8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/pets/_inactive_pets.html.erb
<br />
<% unless @inactive_pets.empty? %>
  <div class="card yellow lighten-4">
    <div class="card-body">
      <h4 class="card-title">Inactive Pets</h4>
      <ul>
        <% for pet in @inactive_pets %>
          <li><%= link_to pet.name, pet_path(pet) %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/pets/_pet_data.html.erb
<div class="card">
  <div class="card-body">
    <h5>Pet Information for <%= @pet.name %></h5><br />

    <b>Owner:&nbsp;&nbsp;</b>
      <%= link_to @pet.owner.proper_name, owner_path(@pet.owner) %><br /><br />

    <b>Type:&nbsp;&nbsp;</b>
      <%= @pet.animal.name %><br /><br />

    <b>Gender:&nbsp;&nbsp;</b>
      <%= @pet.gender %><br /><br />

    <b>Date of Birth:&nbsp;&nbsp;</b>
      <%= @pet.date_of_birth.strftime("%B %d, %Y") %><br /><br />

    <b>Active with PATS?&nbsp;&nbsp;</b>
      <%= @pet.active ? "Yes" : "No" %><br><br><br>
  </div>
</div>

app/views/pets/_recent_visits.html.erb
<div class="card">
  <div class="card-body">
    <h4 class="card-title">Recent Visits</h4>
    <table class="table table-striped table-hover table-borderless">
      <thead>
        <th>Visit</th>
        <th>Weight</th>
      </thead>
        <% for visit in @recent_visits %>
          <tr>
            <td><%= link_to visit.date.strftime("%m/%d/%y"), visit_path(visit) %></td>
          <td>&nbsp;<%= visit.weight %> lbs</td>
          </tr>
        <% end %>
    </table>
  </div>
</div>

app/views/pets/edit.html.erb
<h5>Editing Pet</h5>

<%= render 'form', pet: @pet %>

<p>&nbsp;</p>
<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "pet", 
                                                         primary: "active_pets", 
                                                         secondary: nil,
                                                         sidebar: "inactive_pets"} %>

app/views/pets/new.html.erb
<h5>New Pet</h5>

<%= render 'form', pet: @pet %>

<p>&nbsp;</p>
<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "pet", 
                                                         object: @pet,
                                                         primary: "pet_data", 
                                                         secondary: nil,
                                                         sidebar: "recent_visits"} %>