config/routes.rb
Rails.application.routes.draw do
  # Rails knows that somehow we will add links to certain pages to navigate between them.
  #  As an end user, you would not like to type URLs all the time to go to a certain page and view that certain page to another one.
  # We are very familiar with links: they make our life easy.

  get "/owners", to: "owners#index", as: :owners

  # This will create a owners_path helper method: is going to take me to the combination of "Get and /owners""
  # The prefix is whatever comes before path. The path part is added automatically
  # So owners_path gets me this route -->   get '/owners', to: 'owners#index' and would take me to the index page.
  # Without the helpers, if we would like to specify a link to a certain page, we would need to specify the http verb, and the URI.
  # While with the helpers, we could just say just use owners_path and it would take us to the owners index page.
  # Basically each of the templates in the views has its own helper.

  # GET routes
  get "/owners/new", to: "owners#new", as: :new_owner
  get "/owners/:id/edit", to: "owners#edit", as: :edit_owner
  get "/owners/:id", to: "owners#show", as: :owner

  # Other routes
  post "/owners", to: "owners#create"
  patch "/owners/:id", to: "owners#update"
  delete "/owners/:id", to: "owners#destroy"

  # Helpers are only for Get HTTP requests. No helpers for the operations that happen only at the database level.
  # For Create, Update and Destroy, there is no page to see, again because these just happen behind the scenes,
  # there is no helper provided for this operation. We cannot link to a page for create/Update/Destroy

  # All the above could be simply replaced by
  # resources :owners

  # Resource routes (maps HTTP verbs to controller actions automatically):
  resources :pets
  resources :animals
  resources :visits
  resources :dosages
  resources :treatments
  resources :medicines
  resources :procedures

  # Routes for mecidine and procedure costs
  # In some cases, we would like to create our own routes.
  # For example, let's say we say that there should not be an index page for medicine cost,
  #  If we were to open medicine_cost in PATS, we did not design a whole index page for it, but associated it instead with a particular medicine.
  # A particular cost could be added this way, and the costs  of a certain medicine including the one we added can be displayed only on this one page
  #  in addition to the details of the medicine.
  #  There is no need to create a full index page of all teh costs page with medicine cost.
  # So, in this particular case, we would not want to use resources, but rather create the paths manually.
  #  Add routes for the functions offered only: so, we need a form to add a new medicine_cost.
  # We specify the:
  # - get: my http verb
  # - my URL: medicine_cost/new
  # Map to this controller#action combination, and then this 'as', this is where I am creating for myself a named helper.
  # So if I say new_medicine_cost_path, it would take me to that empty form to fill it and create a new medecine
  get "medicine_costs/new", to: "medicine_costs#new", as: :new_medicine_cost
  get "procedure_costs/new", to: "procedure_costs#new", as: :new_procedure_cost

  post "medicine_costs", to: "medicine_costs#create", as: :medicine_costs
  post "procedure_costs", to: "procedure_costs#create", as: :procedure_costs

  # Semi-static page routes
  get "home", to: "home#index", as: :home
  get "home/about", to: "home#about", as: :about
  get "home/contact", to: "home#contact", as: :contact
  get "home/privacy", to: "home#privacy", as: :privacy
  # You can have the root of your site routed with 'root'
  root "home#index"

  get "home/search", to: "home#search", as: :search
  # Routes for searching
  # get 'medicines/search', to: 'medicines#search', as: :medicine_search
  # get 'owners/search', to: 'owners#search', as: :owner_search
  # get 'pets/search', to: 'pets#search', as: :pet_search



  # Authentication routes
  resources :users


  resources :sessions


  get "users/new", to: "users#new", as: :signup
  get "users/:id/edit", to: "users#edit", as: :edit_current_user


  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  # Relationships
  has_many :procedure_costs
  has_many :treatments
  has_many :visits, through: :treatments

  # Scopes
  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where.not(active: true) }
  
  # Validations
  validates_presence_of :name
  validates_numericality_of :length_of_time, only_integer: true, greater_than: 0
  
  # Other methods
  # attr_accessor :destroyable

  def current_cost
    curr_cost_of_procedure = self.procedure_costs.current    
    return nil if curr_cost_of_procedure.empty?
    curr_cost_of_procedure.first.cost
  end

  # Callbacks
  # before_destroy :is_destroyable?
  # after_rollback :convert_to_inactive

  # private
  # def is_destroyable?
  #   @destroyable = self.treatments.empty?
  # end

  # def convert_to_inactive
  #   if !destroyable.nil? && destroyable == false
  #     self.update_column(:active, false)
  #   end
  #   @destroyable = nil
  # end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController

  before_action :set_procedure, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    # get all visits in reverse chronological order, 10 per page
    @procedures = Procedure.alphabetical.paginate(page: params[:page]).per_page(10)
  end
  
  def show
    # get the cost history for this procedure
    @prices = @procedure.procedure_costs.chronological #.to_a.reverse
  end
  
  def new
    @procedure = Procedure.new
  end
  
  def create
    @procedure = Procedure.new(procedure_params)
    if @procedure.save
      flash[:notice] = "Successfully added #{@procedure.name}."
      redirect_to @procedure
    else
      render action: 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @procedure.update(procedure_params)
      flash[:notice] = "Successfully updated #{@procedure.name}."
      redirect_to @procedure
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @procedure.destroy
    flash[:notice] = "Successfully removed #{@procedure.name}."
    redirect_to procedures_url
  end

    private
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    def procedure_params
      params.require(:procedure).permit(:name, :description, :length_of_time, :active)
    end
end

app/views/procedures/_cost_history.html.erb
<% unless @prices.empty? %>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Cost History</h4>
      <table class="table table-striped table-hover table-borderless">
      <thead>
        <th>Date</th>
        <th class="align_right">Cost</th>
      </thead>
        <% for price in @prices %>
          <tr>
            <td><%= price.start_date.strftime("%b %d, %Y") %></td>
          <td class="align_right"><%= number_to_currency(price.cost/100) %></td>
          </tr>
        <% end %>
    </table>
    </div>
    <div class="card-action">
      <%= link_to "Add a new cost", new_procedure_cost_path(procedure_id: @procedure.id) %>
    </div>
  </div>
<% else %>
  <div class="card grey lighten-3">
    <div class="card-action">
      <%= link_to "Add a new cost", new_procedure_cost_path(procedure_id: @procedure.id) %>
    </div>
  </div>
<% end %>

app/views/procedures/_form.html.erb
<%= simple_form_for(@procedure) do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="form-inputs">
      <%= f.input :name, label_html: { class: 'active' } %>
      <%= f.input :description, label_html: { class: 'active' } %>
      <%= f.input :length_of_time, label_html: { class: 'active' } %>
      <%= f.input :active %>
    </div>
  </div>
  <div class="row">
    <div class="form-actions col-md-8">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/procedures/_procedure_data.html.erb
<div class="card">
  <div class="card-body">
    <h5>Information for <%= @procedure.name %></h5><br />

    <b>Description:&nbsp;&nbsp;</b>
      <%= @procedure.description %><br /><br />

    <b>Time to perform:&nbsp;&nbsp;</b>
      <%= @procedure.length_of_time %> minutes<br /><br />

    <b>Currently offered?&nbsp;&nbsp;</b>
      <%= @procedure.active ? "Yes" : "No" %><br><br><br>
  </div>
</div>

app/views/procedures/_procedures_list.html.erb
<h4>Procedures at PATS</h4>

<table class="table table-striped table-hover table-borderless">
  <thead>
    <th>Name</th>
    <th class="align_center">Minutes</th>
    <th class="align_center">Current Cost</th>
    <th class="align_center">Options</th>
  </thead>
  <% for procedure in @procedures %>
    <tr>
      <td><%= link_to procedure.name, procedure_path(procedure) %></td>
      <td class="align_center"><%= procedure.length_of_time %></td>
      <td class="align_center"><%= procedure.current_cost.nil? ? 'N/A' : number_to_currency(procedure.current_cost/100) %></td>
      <td class="align_center">
      <%= link_to edit_procedure_path(procedure) do %>
            <i class="bi bi-pencil text-primary"></i>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to(procedure_path(procedure), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
            <i class="bi bi-trash text-primary"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<br />
<%= will_paginate @procedures, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<p>&nbsp;</p>
<%= render :partial => "partials/add_new_object", locals: {model_name: 'procedure'} %>

app/views/procedures/edit.html.erb
<h5>Editing Procedure</h5>

<%= render 'form', procedure: @procedure %>

<p>&nbsp;</p>
<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "procedure", 
                                                         primary: "procedures_list", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/procedures/new.html.erb
<h5>New Procedure</h5>

<%= render 'form', procedure: @procedure %>

<p>&nbsp;</p>
<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "procedure", 
                                                         object: @procedure,
                                                         primary: "procedure_data", 
                                                         secondary: nil,
                                                         sidebar: "cost_history"} %>